name: MacOS

on: 
  push:
  
jobs:
  MacOS:     
    name: MacOS build of LLVM15 
    runs-on: macos-12
    env:
      QT_VER: 5.15.2
      QT_VER_MAIN: 5
    steps:
      - name: Checkout Upstream Repo
        uses: actions/checkout@v3
        with:
          repository: Nekotekina/rpcs3 # RPCS3/rpcs3 # 
          ref: typei # Qt6-fun # 07395dd8fa0848268ad9818fc43a216bd3da5a1c # master #
          submodules: recursive
      - name: Checkout AppImage Repo
        uses: actions/checkout@v3
        with:
            clean: false
            path: ci      
      #- name: cache
      #  uses: actions/cache@v3
      #  with:
      #    path: ~/.ccache
      #    key: build-ccache-Qt${{ env.QT_VER_MAIN }}-${{ env.GITHUB_RUN_ID }}
      #    restore-keys: |
      #      build-ccache-Qt${{ env.QT_VER_MAIN }}
      #      build-ccache
      #- uses: actions/setup-python@v3
      #  with:
      #    python-version: '3.10'
      #- uses: actions/setup-go@v3
      #  with:
      #    go-version: '>=1.19.0'

      - name: Install packages
        run: |
          echo "MacPorts 2.8.1"
          git clone https://github.com/macports/macports-base.git
          cd macports-base
          ./configure && make && sudo make install
          export PATH=/opt/local/bin:$PATH
          echo PATH=/opt/local/bin:$PATH >> $GITHUB_ENV
          sudo port selfupdate
          cd ..
          pwd
          sudo port install libsdl2 qt5 llvm-15 clang-15 ninja nasm ccache glew vulkan-loader vulkan-headers
          sudo cp ci/sources.conf /opt/local/etc/macports/
          sudo mkdir -p /opt/local/ports/graphics/MoltenVK
          sudo cp ci/Portfile /opt/local/ports/graphics/MoltenVK/
          cd /opt/local/ports
          sudo portindex
          sudo port install MoltenVK
          #ls !break
          #brew install llvm --HEAD
          #brew install -f --overwrite nasm ninja create-dmg ccache sdl2 glew
          #arch -x86_64 /usr/local/homebrew/bin/brew install -f --overwrite zstd llvm 
          #pip install --upgrade pip
          
      #- name: Install Qt
      #  run: |
      #    curl -sLO https://files.pythonhosted.org/packages/47/42/351389ca36c7adfc5f4e92d086cdb2bdbde13f1b89ee882f4a1cab2183ac/yaqti-2021.7.29-py3-none-any.whl
      #    python3 -m pip install yaqti-2021.7.29-py3-none-any.whl
      #    pyver=$(python3 --version | awk '{print $2}')
      #    curl -sL https://raw.githubusercontent.com/qurious-pixel/yaqti/fetch/yaqti/fetchers.py -o $HOME/hostedtoolcache/Python/$pyver/x64/lib/python${pyver%.*}/site-packages/yaqti/fetchers.py
      #    python -m yaqti install --os mac --platform desktop --version ${{ env.QT_VER }} --modules qtmultimedia --set-envs --install-deps

      #- name: Install Qt5
      #  run: |
      #    git clone https://github.com/engnr/qt-downloader.git
      #    cd qt-downloader
      #    git checkout f52efee0f18668c6d6de2dec0234b8c4bc54c597
      #    pip3 install pipenv
      #    pipenv run pip3 install py7zr requests semantic_version lxml
      #    mkdir -p ${{ env.QT_VER }}/clang_64/bin/
      #    mkdir -p ${{ env.QT_VER }}/clang_64/mkspecs/
      #    touch ${{ env.QT_VER }}/clang_64/mkspecs/qconfig.pri
      #    PIPENV_VERBOSE=true pipenv run ./qt-downloader macos desktop ${{ env.QT_VER }} clang_64 --addons qtmultimedia --opensource
      #    cd ..
          
      - name: Environmental Variables
        run: |
          echo CXX="/opt/local/bin/clang++-mp-15" >> $GITHUB_ENV
          echo CC="/opt/local/bin/clang-mp-15" >> $GITHUB_ENV
          echo CMAKE_EXTRA_OPTS='-DLLVM_TARGETS_TO_BUILD=X86' >> $GITHUB_ENV
          export WORKDIR="$(pwd)"
          echo WORKDIR="$(pwd)" >> $GITHUB_ENV
          #echo PATH="$BREW_PATH/opt/ccache/libexec:$BREW_PATH/opt/llvm/bin:$WORKDIR/qt-downloader/${{ env.QT_VER }}/clang_64/bin:$BREW_BIN:$BREW_SBIN:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:$PATH" >> $GITHUB_ENV
          echo LDFLAGS="-Wl,-rpath,$BREW_X64_PATH/lib" >> $GITHUB_ENV
          echo CPPFLAGS="-msse -msse2 -mcx16 -no-pie" >> $GITHUB_ENV
          #echo LIBRARY_PATH="$BREW_X64_PATH/lib" >> $GITHUB_ENV
          #echo LD_LIBRARY_PATH="$BREW_X64_PATH/lib" >> $GITHUB_ENV
          echo LLVM_DIR="/opt/local/libexec/llvm-15/lib/cmake/llvm" >> $GITHUB_ENV
          echo RANLIB="/opt/local/bin/llvm-ranlib-mp-15" >> $GITHUB_ENV
          echo AR="/opt/local/bin/llvm-ar-mp-15" >> $GITHUB_ENV

      - name: Fixes
        run: |
          echo "fixes"
          sed -i '' "s/extern const double NSAppKitVersionNumber;/const double NSAppKitVersionNumber = 1343;/g" 3rdparty/hidapi/hidapi/mac/hid.c
          sed -i '' -e 's/GLEW 1.13.0/GLEW/g' 3rdparty/CMakeLists.txt
          #mv "$BREW_PATH"/opt/llvm/lib/cmake/llvm/Findzstd.cmake "$BREW_PATH"/opt/llvm/lib/cmake/llvm/Findzstd.cmake.old
          #curl -sSfl https://raw.githubusercontent.com/llvm/llvm-project/main/llvm/cmake/modules/Findzstd.cmake -o "$BREW_PATH"/opt/llvm/lib/cmake/llvm/Findzstd.cmake
          #diff "$BREW_PATH"/opt/llvm/lib/cmake/llvm/Findzstd.cmake "$BREW_PATH"/opt/llvm/lib/cmake/llvm/Findzstd.cmake.old

      - name: Build RPCS3
        run: |
          ccache --version; ccache -z
          mkdir build && cd build || exit 1
          cmake .. \
              -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
              -DUSE_SDL=ON -DUSE_DISCORD_RPC=OFF -DUSE_VULKAN=ON -DUSE_ALSA=OFF -DUSE_PULSE=OFF -DUSE_AUDIOUNIT=ON \
              -DWITH_LLVM=ON \
              -DUSE_NATIVE_INSTRUCTIONS=OFF \
              -DUSE_SYSTEM_MVK=ON \
              $CMAKE_EXTRA_OPTS \
              -G Ninja
          ninja; build_status=$?;
          ccache -s
           
      #- name: Upload artifacts
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: RPCS3
      #    path: bin/rpcs3.app
