name: Qt6

on: 
  push:
  
jobs:
  Qt6:
    name: build Qt6 from src ubuntu-18.04
    runs-on: ubuntu-18.04
    env:
      qtver: 6.4.2
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: Install cmake
        run: |
          pip install cmake
          cmake --version
      - name: Download QT6 source
        run: |
          echo ${{env.qtver}}
          echo ${{env.qtver%.*}}
          wget https://download.qt.io/official_releases/qt/6.4/${{env.qtver}}/single/qt-everywhere-src-${{env.qtver}}.tar.xz
          tar xf qt-everywhere-src-${{env.qtver}}.tar.xz
          cd qt-everywhere-src-${{env.qtver}}
          ./configure -prefix /usr/local/Qt6
          cmake --build .
          sudo cmake --install .
          ls /usr/local/Qt6 || true
