name: MacOS

on: 
  push:
    #branches: main
  
jobs:
  MacOS:     
    name: MacOS build of Qt6 
    runs-on: macos-12
    env:
      QT_VER: 6.4.2
      QT_VER_MAIN: 6
    steps:
      - name: Checkout Upstream Repo
        uses: actions/checkout@v3
        with:
          repository: Megamouse/rpcs3 # RPCS3/rpcs3 # 
          ref: Qt6-fun # 07395dd8fa0848268ad9818fc43a216bd3da5a1c # master #
          submodules: recursive
      #- name: Checkout AppImage Repo
      #  uses: actions/checkout@v3
      #  with:
      #      clean: false
      #      path: ci      
      - name: cache
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: build-ccache-Qt${{ env.QT_VER_MAIN }}-${{ env.GITHUB_RUN_ID }}
          restore-keys: |
            build-ccache-Qt${{ env.QT_VER_MAIN }}
            build-ccache
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'

      - name: Install packages
        run: |
          brew install -f --overwrite llvm@14 ccache cmake nasm ninja git p7zip create-dmg 
          #pip install --upgrade pip
          
      - name: Environmental Variables
        run: |
          echo BREW_PATH="$(brew --prefix)" >> $GITHUB_ENV
          export BREW_PATH="$(brew --prefix)"
          echo CXX="$BREW_PATH/opt/llvm@14/bin/clang++" >> $GITHUB_ENV
          echo CC="$BREW_PATH/opt/llvm@14/bin/clang" >> $GITHUB_ENV
          echo BREW_X64_PATH="$("/usr/local/homebrew/bin/brew" --prefix)" >> $GITHUB_ENV
          export BREW_X64_PATH="$("/usr/local/homebrew/bin/brew" --prefix)"
          echo BREW_BIN="/usr/local/bin" >> $GITHUB_ENV
          export BREW_BIN="/usr/local/bin"
          echo BREW_SBIN="/usr/local/sbin" >> $GITHUB_ENV
          export BREW_SBIN="/usr/local/sbin"
          echo CMAKE_EXTRA_OPTS='-DLLVM_TARGETS_TO_BUILD=X86' >> $GITHUB_ENV
          export WORKDIR="$(pwd)"
          echo WORKDIR="$(pwd)" >> $GITHUB_ENV
          export Qt6_PREFIX="$WORKDIR/qt-downloader/${{ env.QT_VER }}/macos"
          echo Qt6_PREFIX="$WORKDIR/qt-downloader/${{ env.QT_VER }}/macos" >> $GITHUB_ENV
          export Qt6_DIR="$Qt6_PREFIX/lib/cmake/Qt${{ env.QT_VER_MAIN }}"
          echo Qt6_DIR="$Qt6_PREFIX/lib/cmake/Qt${{ env.QT_VER_MAIN }}" >> $GITHUB_ENV
          echo SDL2_DIR="$BREW_X64_PATH/opt/sdl2/lib/cmake/SDL2" >> $GITHUB_ENV
          echo PATH="$BREW_PATH/opt/ccache/libexec:$BREW_PATH/opt/llvm@14/bin:$WORKDIR/qt-downloader/${{ env.QT_VER }}/clang_64/bin:$BREW_BIN:$BREW_SBIN:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:$PATH" >> $GITHUB_ENV
          echo LDFLAGS="-L$BREW_X64_PATH/lib -Wl,-rpath,$BREW_X64_PATH/lib" >> $GITHUB_ENV
          echo CPPFLAGS="-I$BREW_X64_PATH/include -msse -msse2 -mcx16 -no-pie" >> $GITHUB_ENV
          echo LIBRARY_PATH="$BREW_X64_PATH/lib" >> $GITHUB_ENV
          echo LD_LIBRARY_PATH="$BREW_X64_PATH/lib" >> $GITHUB_ENV
          echo CCACHE_DIR=~/.ccache >> $GITHUB_ENV

      - name: Fixes
        run: |
          echo "fixes"

      - name: Install Qt6
        run: |
          git clone https://github.com/engnr/qt-downloader.git
          cd qt-downloader
          git checkout f52efee0f18668c6d6de2dec0234b8c4bc54c597
          pip3 install pipenv
          pipenv run pip3 install py7zr requests semantic_version lxml
          mkdir -p ${{ env.QT_VER }}/clang_64/bin/
          mkdir -p ${{ env.QT_VER }}/clang_64/mkspecs/
          touch ${{ env.QT_VER }}/clang_64/mkspecs/qconfig.pri
          PIPENV_VERBOSE=true pipenv run ./qt-downloader macos desktop ${{ env.QT_VER }} clang_64 --addons qtmultimedia --opensource
          cd ..
      
      - name: Build ccache
        run: |
          mkdir -p simple-project/build
          cd simple-project/build
          clang++ --version
          cmake .. -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER=clang++
          ccache -s
          echo $CCACHE_DIR
          ls ~/.ccache 
      #- name: Upload artifacts
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: RPCS3
      #    path: bin/rpcs3.app
