name: Qt6

on: 
  push:
  
jobs:
  Qt6:
    name: build Qt6 from src ubuntu-18.04
    runs-on: ubuntu-18.04
    env:
      qtver: 6.4.2
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: Install cmake
        run: |
          pip install cmake
          cmake --version
      - name: Install packages
        run: |
          sudo apt install bison build-essential clang flex gperf \
          libatspi2.0-dev libbluetooth-dev libclang-dev libcups2-dev libdrm-dev \
          libegl1-mesa-dev libfontconfig1-dev libfreetype6-dev \
          libgstreamer1.0-dev libhunspell-dev libnss3-dev libopengl0 \
          libpulse-dev libssl-dev libts-dev libx11-dev libx11-xcb-dev \
          libxcb-glx0-dev libxcb-icccm4-dev libxcb-image0-dev \
          libxcb-keysyms1-dev libxcb-randr0-dev libxcb-render-util0-dev \
          libxcb-shape0-dev libxcb-shm0-dev libxcb-sync-dev libxcb-util-dev \
          libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-xkb-dev libxcb1-dev \
          libxcomposite-dev libxcursor-dev libxdamage-dev libxext-dev \
          libxfixes-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev \
          libxkbfile-dev libxrandr-dev libxrender-dev libxshmfence-dev \
          libxshmfence1 llvm ninja-build nodejs
      - name: Download QT6 source
        run: |
          echo ${{env.qtver}}
          QTVERMIN=$(echo ${{env.qtver}} | cut -b -3)
          echo $QTVERMIN
          wget https://download.qt.io/official_releases/qt/{$QTVERMIN}/${{env.qtver}}/single/qt-everywhere-src-${{env.qtver}}.tar.xz
          tar xf qt-everywhere-src-${{env.qtver}}.tar.xz
          cd qt-everywhere-src-${{env.qtver}}
          ./configure -prefix /usr/local/Qt6
          cmake --build .
          sudo cmake --install .
          ls /usr/local/Qt6 || true
