name: MacOS

on: 
  push:
  
jobs:
  MacOS:     
    name: MacOS build of Qt6 
    runs-on: macos-12
    env:
      QT_VER: 6.4.2
      QT_VER_MAIN: 6
    steps:
      - name: Checkout Upstream Repo
        uses: actions/checkout@v3
        with:
          repository: Megamouse/rpcs3 # RPCS3/rpcs3 # 
          ref: 9a0490114383403f00f53dabf0373b75f132685e # Qt6-fun # master #
          submodules: recursive
      - name: Checkout AppImage Repo
        uses: actions/checkout@v3
        with:
            clean: false
            path: ci      
      - name: cache
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: build-ccache-Qt${{ env.QT_VER_MAIN }}-${{ env.GITHUB_RUN_ID }}
          restore-keys: |
            build-ccache-Qt${{ env.QT_VER_MAIN }}
            build-ccache
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'

      - name: Install packages
        run: |
          brew install -f --overwrite llvm@14 nasm ninja git p7zip create-dmg ccache cmake SDL2 glew
          pip install --upgrade pip

      #- name: Install Qt
      #  run: |
      #    curl -sLO https://files.pythonhosted.org/packages/47/42/351389ca36c7adfc5f4e92d086cdb2bdbde13f1b89ee882f4a1cab2183ac/yaqti-2021.7.29-py3-none-any.whl
      #    python3 -m pip install yaqti-2021.7.29-py3-none-any.whl
      #    pyver=$(python3 --version | awk '{print $2}')
      #    curl -sL https://raw.githubusercontent.com/qurious-pixel/yaqti/fetch/yaqti/fetchers.py -o $HOME/hostedtoolcache/Python/$pyver/x64/lib/python${pyver%.*}/site-packages/yaqti/fetchers.py
      #    python -m yaqti install --os mac --platform desktop --version ${{ env.QT_VER }} --modules qtmultimedia --set-envs --install-deps

      - name: Install Qt6
        run: |
          git clone https://github.com/engnr/qt-downloader.git
          cd qt-downloader
          git checkout f52efee0f18668c6d6de2dec0234b8c4bc54c597
          pip3 install pipenv
          pipenv run pip3 install py7zr requests semantic_version lxml
          mkdir -p ${{ env.QT_VER }}/clang_64/bin/
          mkdir -p ${{ env.QT_VER }}/clang_64/mkspecs/
          touch ${{ env.QT_VER }}/clang_64/mkspecs/qconfig.pri
          PIPENV_VERBOSE=true pipenv run ./qt-downloader macos desktop ${{ env.QT_VER }} clang_64 --module qtmultimedia --opensource
          cd ..
      
      - name: Environmental Variables
        run: |
          echo CXX=clang++ >> $GITHUB_ENV
          echo CC=clang >> $GITHUB_ENV
          echo BREW_PATH="$(brew --prefix)" >> $GITHUB_ENV
          echo BREW_X64_PATH="$("/usr/local/homebrew/bin/brew" --prefix)" >> $GITHUB_ENV
          echo BREW_BIN="/usr/local/bin" >> $GITHUB_ENV
          echo BREW_SBIN="/usr/local/sbin" >> $GITHUB_ENV
          echo CMAKE_EXTRA_OPTS='-DLLVM_TARGETS_TO_BUILD=X86' >> $GITHUB_ENV
          export WORKDIR="$(pwd)"
          echo Qt6_DIR="$WORKDIR/qt-downloader/${{ env.QT_VER }}/clang_64/lib/cmake/Qt${{ env.QT_VER_MAIN }}" >> $GITHUB_ENV
          echo SDL2_DIR="$BREW_X64_PATH/opt/sdl2/lib/cmake/SDL2" >> $GITHUB_ENV
          echo PATH="$BREW_PATH/opt/llvm@14/bin:$WORKDIR/qt-downloader/${{ env.QT_VER }}/clang_64/bin:$BREW_BIN:$BREW_SBIN:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:$PATH" >> $GITHUB_ENV
          echo LDFLAGS="-L$BREW_X64_PATH/lib -Wl,-rpath,$BREW_X64_PATH/lib" >> $GITHUB_ENV
          echo CPPFLAGS="-I$BREW_X64_PATH/include -msse -msse2 -mcx16 -no-pie" >> $GITHUB_ENV
          echo LIBRARY_PATH="$BREW_X64_PATH/lib" >> $GITHUB_ENV
          echo LD_LIBRARY_PATH="$BREW_X64_PATH/lib" >> $GITHUB_ENV

      - name: Fixes
        run: |
          echo "fixes"
          sed -i '' "s/extern const double NSAppKitVersionNumber;/const double NSAppKitVersionNumber = 1343;/g" 3rdparty/hidapi/hidapi/mac/hid.c

      - name: Build RPCS3
        run: |
          mkdir build && cd build || exit 1
          cmake .. \
              -DUSE_SDL=ON -DUSE_DISCORD_RPC=OFF -DUSE_VULKAN=ON -DUSE_ALSA=OFF -DUSE_PULSE=OFF -DUSE_AUDIOUNIT=ON \
              -DLLVM_CCACHE_BUILD=OFF -DLLVM_BUILD_RUNTIME=OFF -DLLVM_BUILD_TOOLS=OFF \
              -DLLVM_INCLUDE_DOCS=OFF -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_TESTS=OFF -DLLVM_INCLUDE_TOOLS=OFF \
              -DLLVM_INCLUDE_UTILS=OFF -DLLVM_USE_PERF=OFF -DLLVM_ENABLE_Z3_SOLVER=OFF \
              -DUSE_NATIVE_INSTRUCTIONS=OFF \
              -DUSE_SYSTEM_MVK=OFF \
              $CMAKE_EXTRA_OPTS \
              -DLLVM_TARGET_ARCH=X86_64 -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_IGNORE_PATH="$BREW_PATH/lib" \
              -G Ninja
          "$BREW_PATH/bin/ninja"; build_status=$?;
           
      #- name: Upload artifacts
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: RPCS3
      #    path: artifacts/
