name: Qt6

on: 
  push:
  
jobs:
  Qt6:
    name: build Qt6 from src ubuntu-18.04
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download source
        run: |
          wget https://download.qt.io/official_releases/qt/6.4/6.4.0/single/qt-everywhere-src-6.4.0.tar.xz
          tar xf qt-everywhere-src-6.4.0.tar.xz
          cd qt-everywhere-src-6.4.0
          ./configure -prefix /usr/local/Qt6
          cmake --build .
          sudo cmake --install .
          ls /usr/local/Qt6 || true
