name: Build RPCS3

defaults:
  run:
    shell: bash
on:
  push:
    branches:
      - master # Only trigger push event on 'master' branch
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

env:
  BUILD_REPOSITORY_NAME: ${{ github.repository }}
  BUILD_SOURCEBRANCHNAME: ${{ github.ref_name }}
  BUILD_SOURCEVERSION: ${{ github.sha }}
  BUILD_ARTIFACTSTAGINGDIRECTORY: ${{ github.workspace }}/artifacts/

jobs:
  FreeBSD_Build:
    # Only run push event on master branch of main repo, but run all PRs
    if: github.event_name != 'push' || (github.repository == 'RPCS3/rpcs3' && github.ref_name == 'master')
    name: RPCS3 FreeBSD 
    runs-on: ubuntu-latest
    env:
      CCACHE_DIR: /tmp/ccache_dir
      CI_HAS_ARTIFACTS: true
      ARTDIR: "/root/artifacts"
      RELEASE_MESSAGE: "/rpcs3/GitHubReleaseMessage.txt"
      #COMPILER: ${{ matrix.compiler }}
      #UPLOAD_COMMIT_HASH: ${{ matrix.UPLOAD_COMMIT_HASH }}
      #UPLOAD_REPO_FULL_NAME: ${{ matrix.UPLOAD_REPO_FULL_NAME }}
      #RUN_UNIT_TESTS: github.event_name == 'pull_request' && 'ON' || 'OFF'
      QT_VER: '6.9.1'
      QT_VER_MAIN: '6'
      LLVM_COMPILER_VER: '19'
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: FreeBSD build
        id: root
        uses: vmactions/freebsd-vm@v1
        with:
          envs: 'QT_VER_MAIN LLVM_COMPILER_VER'
          usesh: true
          prepare: .ci/install-freebsd.sh
          #run: .ci/build-freebsd.sh
            
